repos:
- repo: https://github.com/srstevenson/nb-clean
  rev: 4.0.1
  hooks:
    - id: nb-clean
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
