[tool.ruff]
line-length = 120
exclude = [".git"]

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# Enable import reorder checks (`I`) by default.
select = [
    "E4",
    "E7",
    "E9",
    "F",  # ruff's default
    "I",  # import order check
]

[tool.ruff.format]
quote-style = "single"

