name: Run pre-commit on colab branch

on:
  push:
    branches:
      - colab

permissions:
  contents: write

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: colab
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit (first time, might fail when attempt to auto-fix)
      run: pre-commit run --all-files || true

    - name: Run pre-commit (second time, must pass)
      run: pre-commit run --all-files

    - name: Commit and push changes if needed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "chore: auto-fix with pre-commit [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} colab
        fi
      env:
        COLAB_PAT: ${{ secrets.COLAB_PAT }}
